### ISSUE TITLE
how to use  --local arg ?

### ISSUE THREAD

**Issue by 2492202119** [erikbern/ann-benchmarks#260]
when i try to use --local for below command:
sudo python3 run.py --dataset gist-960-euclidean --algorithm kgraph --force --runs 1 --count 10 --local
report errors:
xxxxxx:~/ann/ann-benchmarks$ sudo python3 run.py --dataset gist-960-euclidean --algorithm kgraph --force --runs 1 --count 10 --local
2021-09-15 04:58:17,994 - annb - INFO - running only kgraph
2021-09-15 04:58:1**7,994 - root - WARNING - ann_benchmarks.algorithms.kgraph.KGraph(['euclidean', {'reverse': -1}, Tru**e]): the module 'ann_benchmarks.algorithms.kgraph' could not be loaded; skipping
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    main()
  File "/home/xxx/ann/ann-benchmarks/ann_benchmarks/main.py", line 234, in main
    raise Exception('Nothing to run')
Exception: Nothing to run
:: it seems script can't parse --local correctly

**Comment by maumueller** [comment]
Does `sudo python3 -c 'import pykgraph'` work on your setup?

**Comment by 2492202119** [comment]
i tried this but it seems no this module:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pykgraph'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 12, in <module>
    import subprocess, tempfile, os.path, re, pwd, grp, os, time, io
  File "/home/lnic/ann/ann-benchmarks/ann_benchmarks/algorithms/subprocess.py", line 7, in <module>
    from ann_benchmarks.data import \
ModuleNotFoundError: No module named 'ann_benchmarks'

Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pykgraph'

**Comment by 2492202119** [comment]
i found a content in Dockerfile.kgraph. it seems we need install kgraph seperately
FROM ann-benchmarks

RUN apt-get update && apt-get install -y libboost-timer-dev libboost-chrono-dev libboost-program-options-dev libboost-system-dev libboost-python-dev
RUN git clone https://github.com/aaalgo/kgraph
RUN cd kgraph && python3 setup.py build && python3 setup.py install
RUN python3 -c 'import pykgraph'

**Comment by maumueller** [comment]
Yes, before running locally you have to make sure that the libraries are actually accessible from your Python installation.
