### ISSUE TITLE
python install.py syntax error

### ISSUE THREAD

**Issue by thompsonbry** [erikbern/ann-benchmarks#418]
I cloned the ann-benchmarks project on Friday and ran into the following issue when trying to install it.  I am not a python person, but it seems likely that there is a problem getting the arguments resulting in a syntax error during evaluation.

sudo python install.py
```
Traceback (most recent call last):
  File "install.py", line 7, in <module>
    from ann_benchmarks.main import positive_int
  File "/home/ec2-user/ann-benchmarks/ann_benchmarks/main.py", line 152
    logger.info(f"running only {args.docker_tag}")
                                                ^
SyntaxError: invalid syntax
```
python --version
```Python 3.10.6```

**Comment by thompsonbry** [comment]
Ah. There were a few issues.  When using sudo, a different python version was in use by root.  When using the current used, ```python install.py``` I was getting some permissions problems.  ```newgrp docker``` unblocked those.
