### ISSUE TITLE
Some datasets are not available (403 Forbidden)

### ISSUE THREAD

**Issue by aosh-ab7e** [erikbern/ann-benchmarks#457]
The following datasets are not available, indicates `403 Forbidden`:
- Kosarak (http://ann-benchmarks.com/kosarak-jaccard.hdf5)
- MovieLens-10M (http://ann-benchmarks.com/movielens10m-jaccard.hdf5)
- Last.fm (http://ann-benchmarks.com/lastfm-64-dot.hdf5)

**Comment by ankane** [comment]
Also seeing this with the `dbpedia-openai-*k-angular` datasets, fwiw

**Comment by maumueller** [comment]
Ping @erikbern

**Comment by erikbern** [comment]
Something is broken with kosarak-jaccard and I'm not able to re-run it:

```
ubuntu@ip-172-31-3-226:~/ann-benchmarks$ python create_dataset.py --dataset kosarak-jaccard
downloading http://fimi.uantwerpen.be/data/kosarak.dat.gz -> kosarak.dat.gz...
Traceback (most recent call last):
  File "/home/ubuntu/ann-benchmarks/create_dataset.py", line 10, in <module>
    DATASETS[args.dataset](fn)
  File "/home/ubuntu/ann-benchmarks/ann_benchmarks/datasets.py", line 597, in <lambda>
    "kosarak-jaccard": lambda out_fn: kosarak(out_fn),
  File "/home/ubuntu/ann-benchmarks/ann_benchmarks/datasets.py", line 452, in kosarak
    X_train, X_test = train_test_split(numpy.array(X), test_size=500, dimension=dimension)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (75462,) + inhomogeneous part.
```

**Comment by erikbern** [comment]
I'm not able to access those files, and it seems like the script to build the datasets have broken.

```
ubuntu@ip-172-31-3-226:~/ann-benchmarks$ python create_dataset.py --dataset kosarak-jaccard
Traceback (most recent call last):
  File "/home/ubuntu/ann-benchmarks/create_dataset.py", line 10, in <module>
    DATASETS[args.dataset](fn)
  File "/home/ubuntu/ann-benchmarks/ann_benchmarks/datasets.py", line 597, in <lambda>
    "kosarak-jaccard": lambda out_fn: kosarak(out_fn),
  File "/home/ubuntu/ann-benchmarks/ann_benchmarks/datasets.py", line 452, in kosarak
    X_train, X_test = train_test_split(numpy.array(X), test_size=500, dimension=dimension)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (75462,) + inhomogeneous part.
```

Not sure how to fix, does anyone know?

Will fix lastfm

**Comment by erikbern** [comment]
Also not able to regenerate `lastfm`:

```
ubuntu@ip-172-31-3-226:~/ann-benchmarks$ python create_dataset.py --dataset lastfm-64-dot
Traceback (most recent call last):
  File "/home/ubuntu/ann-benchmarks/create_dataset.py", line 10, in <module>
    DATASETS[args.dataset](fn)
  File "/home/ubuntu/ann-benchmarks/ann_benchmarks/datasets.py", line 595, in <lambda>
    "lastfm-64-dot": lambda out_fn: lastfm(out_fn, 64),
  File "/home/ubuntu/ann-benchmarks/ann_benchmarks/datasets.py", line 486, in lastfm
    from implicit.approximate_als import augment_inner_product_matrix
ImportError: cannot import name 'augment_inner_product_matrix' from 'implicit.approximate_als' (/home/ubuntu/.local/lib/python3.10/site-packages/implicit/approximate_als.py)
```

Do you know what's the issue @benfred?

**Comment by erikbern** [comment]
NVM I figured out how to fix the original permission issue.

However we should probably fix the issue with the datasets – it would be good to have a way to regenerate them from scratch
