### ISSUE TITLE
Milvus  benchmarking run issue

### ISSUE THREAD

**Issue by pauldintel** [erikbern/ann-benchmarks#471]
Opening new issue as: 
Any pointer what is wrong and what code should be used to connect Milvus database with connection info ? 

~/ann-benchmarks$ sudo python3 run.py --dataset glove-25-angular --algorithm milvus --runs=1
2023-09-29 22:37:12,919 - annb - INFO - running only milvus
Traceback (most recent call last):
File "/home/ubuntu/ann-benchmarks/run.py", line 7, in
main()
File "/home/ubuntu/ann-benchmarks/ann_benchmarks/main.py", line 341, in main
raise Exception("Nothing to run")
Exception: Nothing to run

**Comment by wangting0128** [comment]
You can try executing the following command to see if it works:
`sudo python3 run.py --dataset glove-25-angular --algorithm 'Milvus(Knowhere)'`

**Comment by pauldintel** [comment]
@wangting0128  do you think this code can be reused and replace on module.py to make pymilvus works ? 
https://gitcode.net/mirrors/milvus-io/ann-benchmarks/-/blob/master/ann_benchmarks/algorithms/milvus.py

**Comment by pauldintel** [comment]
yes I tried to reproduce and failed on : import milvus part of the code even if I downgraded pymilvus to older version on python 3.11 . its weird and not sure why its not working !

**Comment by wangting0128** [comment]
> yes I tried to reproduce and failed on : import milvus part of the code even if I downgraded pymilvus to older version on python 3.11 . its weird and not sure why its not working !

pymilvus is working for milvus version >= 2.0

**Comment by cococo2000** [comment]
@pauldintel hi, you can try the latest code. https://github.com/erikbern/ann-benchmarks/pull/517 has updated the code for milvus.
