### ISSUE TITLE
Can you provide an available Ubuntu 22.04 basic image?

### ISSUE THREAD

**Issue by simon28li** [erikbern/ann-benchmarks#553]
As the title, I have many problems with the dependency of the Ubuntu basic image pulled by Docker? Can you provide a downloadable image that I can use directly?
```
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dpkg-dev : Depends: bzip2 but it is not installable
            Recommends: gnupg but it is not installable or
                        gnupg2 but it is not installable
 gcc-7 : Depends: libgcc-7-dev (= 7.5.0-3ubuntu1~18.04) but it is not installable
 libc6-dev : Depends: libc6 (= 2.27-3ubuntu1.6) but 2.35-0ubuntu3.8 is to be installed
             Depends: libc-dev-bin (= 2.27-3ubuntu1.6) but it is not going to be installed
 libstdc++-7-dev : Depends: libgcc-7-dev (= 7.5.0-3ubuntu1~18.04) but it is not installable
 perl : Depends: perl-base (= 5.26.1-6ubuntu0.7) but 5.34.0-3ubuntu1.3 is to be installed
        Recommends: netbase but it is not going to be installed
 perl-base : Breaks: perl (< 5.34.0~) but 5.26.1-6ubuntu0.7 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
The command '/bin/sh -c apt-get install -y python python3-numpy python3-scipy python3-pip build-essential git' returned a non-zero code: 100
Traceback (most recent call last):
  File "/home/li/python3.10/bin/ann-benchmarks/install.py", line 39, in <module>
    subprocess.check_call(
  File "/home/li/python3.10/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker build          --rm -t ann-benchmarks -f ann_benchmarks/algorithms/base/Dockerfile .' returned non-zero exit status 100.
```

**Comment by simon28li** [comment]
By the way, is the ubuntu 22.04 image used in your tests x86 architecture? My test machine aarch64 platform.
