### ISSUE TITLE
"Nothing to run" when specifying algorithm parameter

### ISSUE THREAD

**Issue by Hillier98** [erikbern/ann-benchmarks#555]
Hi, whenever I try to specify an algorithm parameter I get the following error:

```
$ python3 run.py --algorithm faiss_hnsw --dataset mnist-784-euclidean
2024-11-13 13:13:19,992 - annb - INFO - running only faiss_hnsw
Traceback (most recent call last):
  File "/home/test/ann-benchmarks/run.py", line 7, in <module>
    main()
  File "/home/test/ann-benchmarks/ann_benchmarks/main.py", line 344, in main
    raise Exception("Nothing to run")
Exception: Nothing to run
$ python3 run.py --algorithm faiss_hnsw
2024-11-13 13:13:26,071 - annb - INFO - running only faiss_hnsw
Traceback (most recent call last):
  File "/home/test/ann-benchmarks/run.py", line 7, in <module>
    main()
  File "/home/test/ann-benchmarks/ann_benchmarks/main.py", line 344, in main
    raise Exception("Nothing to run")
Exception: Nothing to run
```

However, if I disable the algorithms I don't want to test in the `config.yml` files and then I just run `$ python3 run.py --dataset mnist-784-euclidean` or `$ python3 run.py`, that works. So I think there's a bug; I just thought it may be useful to report it.

**Comment by maumueller** [comment]
Thanks @Hillier98, I can reproduce this and will look into it.

**Comment by raulod** [comment]
I am facing the same issue.

**Comment by raulod** [comment]
a gentle reminder to fix

**Comment by maumueller** [comment]
Sorry, this took me a while. The reason for it not working was more subtle and boiled down to a difference between the folder name and the config name. Since one implementation (e.g., faiss) might support different data structures, these are sometimes only loosely connected. 

`--list-algorithms` with now identify the correct algorithm name, which was `hnsw(faiss)` in your example.
